######################################################################
# Automatically generated by qmake (3.0) ?? ?? 12 16:31:36 2023
######################################################################

TEMPLATE = app
TARGET = Sec01_InstallingEventFilters
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += CustomerInfoDialog.h
SOURCES += CustomerInfoDialog.cc main.cc
