######################################################################
# Automatically generated by qmake (3.0) ?? ??? 14 16:13:59 2022
######################################################################

TEMPLATE = app
TARGET = BuiltinWidgetAndDialogClasses
INCLUDEPATH += .

CONFIG += uitools

# Input
SOURCES += main.cc
