######################################################################
# Automatically generated by qmake (3.0) ?? ?? 11 16:50:46 2023
######################################################################

TEMPLATE = app
TARGET = Sec05_MultipleDocumentInterface
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += Editor.h MainWindow.h
SOURCES += Editor.cc main.cc MainWindow.cc
RESOURCES += mdieditor.qrc
