######################################################################
# Automatically generated by qmake (3.0) ?? ?? 10 15:16:38 2023
######################################################################

TEMPLATE = app
TARGET = Sec03_ScrollingAreas
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += IconEditor.h
SOURCES += IconEditor.cc main.cc build/debug/qrc_iconeditor.cpp
RESOURCES += iconeditor.qrc
