######################################################################
# Automatically generated by qmake (3.0) ?? ?? 6 16:30:59 2023
######################################################################

TEMPLATE = app
TARGET = Sec03_DoubleBuffering
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += PlotSettings.h Plotter.h
SOURCES += main.cc PlotSettings.cc Plotter.cc
RESOURCES += plotter.qrc
