######################################################################
# Automatically generated by qmake (3.0) ?? ?? 9 16:32:58 2023
######################################################################

TEMPLATE = app
TARGET = Sec02_Splitters
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += MailClient.h
SOURCES += MailClient.cc main.cc
