######################################################################
# Automatically generated by qmake (3.0) ?? ?? 6 16:30:22 2023
######################################################################

TEMPLATE = app
TARGET = Sec00_CustomizingQtWidgets
INCLUDEPATH += .

# Input
HEADERS += HexSpinBox.h
SOURCES += HexSpinBox.cc main.cc
