######################################################################
# Automatically generated by qmake (3.0) ?? ?? 13 14:55:30 2023
######################################################################

TEMPLATE = app
TARGET = Sec00_PaintingWithQPainter
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += PaintingWidget.h
SOURCES += main.cc PaintingWidget.cc
