######################################################################
# Automatically generated by qmake (3.0) ?? ?? 12 12:12:39 2023
######################################################################

TEMPLATE = app
TARGET = TimerEvent
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += Ticker.h
SOURCES += main.cc Ticker.cc
