######################################################################
# Automatically generated by qmake (3.0) ?? ??? 19 10:59:20 2022
######################################################################

TEMPLATE = app
TARGET = SubclassingQMainWindow
INCLUDEPATH += . ./ch2_CreatingDialogs/FindDialog ./ch2_CreatingDialogs/GotoCellDialog ./ch2_CreatingDialogs/ShapeChangingDialog

QT += widgets

# Input
HEADERS += mainwindow.h \
           spreadsheet.h \
           cell.h \
           ch2_CreatingDialogs/FindDialog/FindDialog.h \
           ch2_CreatingDialogs/GotoCellDialog/GoToCellDialog.h \
           ch2_CreatingDialogs/ShapeChangingDialog/SortDialog.h \
           /ch2_CreatingDialogs/FindDialog/FindDialog.h \
           /ch2_CreatingDialogs/GotoCellDialog/GoToCellDialog.h \
           /ch2_CreatingDialogs/ShapeChangingDialog/SortDialog.h
FORMS += ch2_CreatingDialogs/GotoCellDialog/forms/GotoCellDialog.ui \
         ch2_CreatingDialogs/ShapeChangingDialog/forms/SortDialog.ui
SOURCES += main.cc \
           mainwindow.cc \
           spreadsheet.cc \
           cell.cc \
           ch2_CreatingDialogs/FindDialog/FindDialog.cc \
           ch2_CreatingDialogs/GotoCellDialog/GoToCellDialog.cc \
           ch2_CreatingDialogs/ShapeChangingDialog/SortDialog.cc
RESOURCES += spreadsheet.qrc