######################################################################
# Automatically generated by qmake (3.1) Mon Dec 26 15:42:19 2022
######################################################################

TEMPLATE = app
TARGET = SubclassingQMainWindow
INCLUDEPATH += .

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += cell.h \
           mainwindow.h \
           spreadsheet.h \
           ch2_CreatingDialogs/FindDialog/FindDialog.h \
           ch2_CreatingDialogs/GotoCellDialog/GoToCellDialog.h \
           ch2_CreatingDialogs/ShapeChangingDialog/SortDialog.h 
           
FORMS += ch2_CreatingDialogs/GotoCellDialog/forms/GotoCellDialog.ui \
         ch2_CreatingDialogs/ShapeChangingDialog/forms/SortDialog.ui
SOURCES += cell.cc \
           main.cc \
           mainwindow.cc \
           spreadsheet.cc \
           ch2_CreatingDialogs/BuiltinWidgetAndDialogClasses/main.cc \
           ch2_CreatingDialogs/DynamicDialog/main.cc \
           ch2_CreatingDialogs/FindDialog/FindDialog.cc \
           ch2_CreatingDialogs/FindDialog/main.cc \
           ch2_CreatingDialogs/GotoCellDialog/GoToCellDialog.cc \
           ch2_CreatingDialogs/GotoCellDialog/main.cc \
           ch2_CreatingDialogs/ShapeChangingDialog/main.cc \
           ch2_CreatingDialogs/ShapeChangingDialog/SortDialog.cc
RESOURCES += spreadsheet.qrc
