######################################################################
# Automatically generated by qmake (3.0) ?? ?? 5 14:44:19 2023
######################################################################

TEMPLATE = app
TARGET = Sec01_SubclassingQWidget
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += IconEditor.h
SOURCES += IconEditor.cc main.cc
