######################################################################
# Automatically generated by qmake (3.0) ?? ?? 10 17:00:03 2023
######################################################################

TEMPLATE = app
TARGET = Sec04_DockWindowsAndToolbars
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += IconEditor.h MainWindow.h
SOURCES += IconEditor.cc main.cc MainWindow.cc
RESOURCES += iconeditor.qrc
