######################################################################
# Automatically generated by qmake (3.0) ?? ?? 6 17:30:00 2023
######################################################################

TEMPLATE = app
TARGET = Sec00_LayingOutWidgetsOnAForm
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += FindFileDialog.h
SOURCES += FindFileDialog.cc main.cc
