######################################################################
# Automatically generated by qmake (3.0) ?? ?? 12 10:29:50 2023
######################################################################

TEMPLATE = app
TARGET = KeyboardEvent
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += CodeEditor.h MainWindow.h
SOURCES += CodeEditor.cc main.cc MainWindow.cc
