######################################################################
# Automatically generated by qmake (3.0) ?? ??? 19 11:10:16 2022
######################################################################

TEMPLATE = app
TARGET = GotoCellDialog
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += GoToCellDialog.h
FORMS += forms/GotoCellDialog.ui
SOURCES += GoToCellDialog.cc main.cc
