######################################################################
# Automatically generated by qmake (3.0) ?? ??? 14 15:08:06 2022
######################################################################

TEMPLATE = app
TARGET = DynamicDialog
INCLUDEPATH += .

CONFIG += uitools

# Input
FORMS += forms/SortDialog.ui
SOURCES += main.cc
